// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: '系統架構',
      link: {
        type: 'generated-index',
        title: '系統架構',
        description: '派車系統整體架構、模組職責與資料流說明。',
        slug: '/category/architecture',
      },
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: '派車系統網頁操作',
      link: {
        type: 'generated-index',
        title: '派車系統網頁操作',
        description: 'GPM AGVS 派車系統 Web 介面操作說明。',
        slug: '/category/guide',
      },
      items: [{ type: 'autogenerated', dirName: 'guide' }],
    },
    {
      type: 'category',
      label: '車載系統網頁操作',
      link: {
        type: 'generated-index',
        title: '車載系統網頁操作',
        description: 'GPM AGV 車載 HMI Web 介面操作說明。',
        slug: '/category/vehicle-guide',
      },
      items: [{ type: 'autogenerated', dirName: 'vehicle-guide' }],
    },
    {
      type: 'category',
      label: 'SOP 手順',
      link: {
        type: 'doc',
        id: 'sop/index',
      },
      items: [{ type: 'autogenerated', dirName: 'sop' }],
    },
    {
      type: 'category',
      label: 'Alarm Code',
      link: {
        type: 'doc',
        id: 'alarm-code/index',
      },
      items: [
        'alarm-code/dispatch-alarm-code',
        'alarm-code/vehicle-alarm-code',
      ],
    },
    {
      type: 'category',
      label: '常見問題',
      link: {
        type: 'generated-index',
        title: '常見問題',
        description: '整合、派車與 API 使用上的常見問答。',
        slug: '/category/faq',
      },
      items: [{ type: 'autogenerated', dirName: 'faq' }],
    },
  ],

  apiSidebar: [
    'api/overview',
    {
      type: 'category',
      label: 'VMS API',
      link: {
        type: 'generated-index',
        title: 'VMS RESTful API',
        description: 'VMS 提供給 AGV 呼叫的 RESTful API。',
        slug: '/category/vms-api',
      },
      items: ['api/vms-agv'],
    },
    {
      type: 'category',
      label: 'AGV API',
      link: {
        type: 'generated-index',
        title: 'AGV RESTful API',
        description: 'AGV 車載系統提供給 VMS 呼叫的 RESTful API。',
        slug: '/category/agv-api',
      },
      items: ['api/agv-api'],
    },
  ],
};

export default sidebars;
